image: docker:19.03.1

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - name: docker:19.03.1-dind
    command: ["--insecure-registry", "registry.gitlab.cav.xetid.cu", "--insecure-registry", "docker.artifactory.cav.xetid.cu", "--registry-mirror", "https://docker.artifactory.cav.xetid.cu"]

stages:
  - build
  - push
  - deploy_to_prod_xutil

build_project:
  stage: build
  image: maven:3-jdk-11-slim
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  cache:
    paths:
      - .m2/repository
  artifacts:
    paths:
      - target/*.jar
  script:
    - |
      if [ "x$MAVEN_PROXY_HOST" != "x" ] ; then \
          export MAVEN_OPTS="$MAVEN_OPTS -Dhttp.proxyHost=$MAVEN_PROXY_HOST -Dhttp.proxyPort=$MAVEN_PROXY_PORT" && \
          export MAVEN_OPTS="$MAVEN_OPTS -Dhttps.proxyHost=$MAVEN_PROXY_HOST -Dhttps.proxyPort=$MAVEN_PROXY_PORT" && \
          echo "Maven proxy configured!" \
          ; fi ;
    - mvn clean package -B

push_image:
  stage: push
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - if [ "x$CI_COMMIT_BRANCH" != "x" ]; then export CURRENT_BRANCH_NAME=$CI_COMMIT_BRANCH; else export CURRENT_BRANCH_NAME=$CI_DEFAULT_BRANCH; fi
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CURRENT_BRANCH_NAME
    - if [ "x$CI_COMMIT_TAG" != "x" ]; then docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG; fi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE

deploy_to_prod_xutil:
  stage: deploy_to_prod_xutil
  only:
    - master
  dependencies: []
  image:
    name: bitnami/kubectl:1.22.1
    entrypoint: [""]
  script:
    - export KUBECONFIG=$XUTIL_KUBE_CONFIG_FILE
    - kubectl patch deployment pdf-signer -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"build\":\"$CI_COMMIT_SHORT_SHA\"}}}}}}"
